### ISSUE TITLE
python3 pay模块 无法载入smart_unicode

### ISSUE THREAD

**Issue by 23233** [gusibi/python-weixin#11]
### 表现
* python3.6  from weixin.pay import WXAppPay

```ImportError: cannot import name 'smart_unicode'```

#### 仔细看了一下 这个smart_unicode是向py2做的兼容 但是在一个函数中又有引用 哥们 能帮忙更新一下判断py3别载入这个东东么!

**Comment by gusibi** [comment]
感谢反馈，已修复
