### ISSUE TITLE
python3不兼容

### ISSUE THREAD

**Issue by coodrag** [gusibi/python-weixin#13]
调用统一支付接口的时候报错，按以下改动后可以正常运行了

1.
\weixin\pay.py", line 41, in params_filter
    ks.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'

以下代码
ks = params.keys()
ks.sort()
改为
if six.PY3:
    ks = sorted(params)
else:
    ks = params.keys()
    ks.sort()

2.
\weixin\pay.py", line 65, in build_mysign
    return md5(prestr).hexdigest().upper()
TypeError: Unicode-objects must be encoded before hashing

以下代码
prestr += '&key=%s' % str(key)
return md5(prestr).hexdigest().upper()
改为
prestr += '&key=%s' % str(key)
if six.PY3:
    prestr = prestr.encode("utf8")
return md5(prestr).hexdigest().upper()

**Comment by gusibi** [comment]
感谢反馈 已修复

https://github.com/gusibi/python-weixin/commit/147f2d6e717e126ab4f19e949447abc5e8d837f6
