### ISSUE TITLE
微信小程序与django,前端如何格式化数据？

### ISSUE THREAD

**Issue by ricemi189** [gusibi/python-weixin#19]
你好，通过小程序向django提交表单，失败多次，看到你的文章
https://blog.csdn.net/wyaspnet/article/details/76187187
-----------------下面的代码写在小程序里好像不对啊。能否给个源代码-----------
json2form: yfunction json2form(jsonobj){ 
var str=[]; 
for(var p in jsonobj){ 
str.push(encodeURIComponent(p)+”=”+ encodeURIComponent(jsonobj[p])); 
} 
return str.join(“&”); 
}

**Comment by gusibi** [comment]
[Facepalm]  不是我的文章 只是用了这个包  🤣
