### ISSUE TITLE
weixin小程序登陆

### ISSUE THREAD

**Issue by guanyibing** [gusibi/python-weixin#3]
1.OAuth2API里面没有找到获取openid的方法，openid难道是要反向解密user_info才有吗，但我看小程序开发者文档openid跟session_key是可以用code换取得，access_token反倒没提
2.另外，消息模板没有封装回复消息方法吗，需自己调微信相关接口？

**Comment by gusibi** [comment]
问题1：

是的 openid 只能反向解密user_info 才能取到，大致流程是这样，可以参考下
`
api = WXAPPAPI(appid=WXAPP_APPID, app_secret=WXAPP_SECRET)
try:
        session_info = api.exchange_code_for_session_key(code=code)
except OAuth2AuthExchangeError:
        raise Unauthorized('invalid_code')
session_key = session_info.get('session_key')
crypt = WXBizDataCrypt(WXAPP_APPID, session_key)
# encrypted_data 包括敏感数据在内的完整用户信息的加密数据
# iv 加密算法的初始向量
# 这两个参数需要js获取
user_info = crypt.decrypt(encrypted_data, iv)
openid = user_info.get('openId')
`

问题2： 模板消息这个 api 漏掉了， 我最近加一下

感谢反馈

**Comment by gusibi** [comment]
```
from weixin.response import WXResponse
from weixin.reply import WXReply, TextReply, ArticleReply

这两个里面是关于消息回复的相关使用方法，可能会用的到
```

**Comment by imWildCat** [comment]
WXBizDataCrypt 這個怎麼 import？

**Comment by gusibi** [comment]
from weixin.lib.wxcrypt import WXBizDataCrypt
