### ISSUE TITLE
unionId无法获取到

### ISSUE THREAD

**Issue by weibn** [gusibi/python-weixin#49]
你好，最近的使用中，发现  “Python 实现小程序登录注册” 这一功能，通过iv,code 登录后解密的用户信息中没有 **unionid**，这是微信返回数据做了限制还是代码修改的问题呢

**Comment by gusibi** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/login/auth.code2Session.html

https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/union-id.html

可以看下是不是符合获取的条件

UnionID获取途径
绑定了开发者帐号的小程序，可以通过以下途径获取 UnionID。

调用接口 wx.getUserInfo，从解密数据中获取 UnionID。注意本接口需要用户授权，请开发者妥善处理用户拒绝授权后的情况。

如果开发者帐号下存在同主体的公众号，并且该用户已经关注了该公众号。开发者可以直接通过 wx.login + code2Session 获取到该用户 UnionID，无须用户再次授权。

如果开发者帐号下存在同主体的公众号或移动应用，并且该用户已经授权登录过该公众号或移动应用。开发者也可以直接通过 wx.login + code2Session 获取到该用户 UnionID ，无须用户再次授权。

用户在小程序（暂不支持小游戏）中支付完成后，开发者可以直接通过getPaidUnionId接口获取该用户的 UnionID，无需用户授权。注意：本接口仅在用户支付完成后的5分钟内有效，请开发者妥善处理。

小程序端调用云函数时，如果开发者帐号下存在同主体的公众号，并且该用户已经关注了该公众号，可在云函数中通过 cloud.getWXContext 获取 UnionID。

小程序端调用云函数时，如果开发者帐号下存在同主体的公众号或移动应用，并且该用户已经授权登录过该公众号或移动应用，也可在云函数中通过 cloud.getWXContext 获取 UnionID。

**Comment by gusibi** [comment]
暂时先关闭了
