### ISSUE TITLE
请问有没有给微信用户推送消息的api?

### ISSUE THREAD

**Issue by dlooto** [gusibi/python-weixin#51]
请问一下, 这个sdk有没有提供  从服务端给微信用户推送消息的api? 谢谢

**Comment by gusibi** [comment]
微信公号API支持  
- custom_message_send
- template_message_send

**Comment by gusibi** [comment]
可以参考这个文件weixin/client.py

**Comment by dlooto** [comment]
好的, 谢谢! 我们用另外一种方式实现了
