### ISSUE TITLE
阿里云服务器中python-wexin失效？

### ISSUE THREAD

**Issue by trueto** [gusibi/python-weixin#7]
我在本地服务器可以拿到用户的openid，
但部署到阿里云服务器后死活取不到啊，状态码是500.
我尝试用requests访问外部链接是成功的，说明服务器配置没问题啊。

**Comment by gusibi** [comment]
状态码500？ 是哪一步500 
请求微信服务器的时候？
具体什么错误 可以贴一下

**Comment by hadesleejs** [comment]
![qq 20170902112642](https://user-images.githubusercontent.com/7189444/29992581-a43cb254-8fd1-11e7-8b02-9c406c777da6.png)
对encrypted_data 解码报500错误，

**Comment by gusibi** [comment]
这个 先转成 字符串再解码 不用 unicode 试试
